INSERT INTO lk_city (provinceID,cityName) VALUES
	 (51,'Jembrana'),
	 (51,'Tabanan'),
	 (51,'Buleleng'),
	 (51,'Karangasem'),
	 (51,'Klungkung'),
	 (51,'Bangli'),
	 (51,'Gianyar'),
	 (51,'Badung'),
	 (51,'Denpasar'),
	 (19,'Bangka Selatan');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (19,'Bangka Tengah'),
	 (19,'Belitung Timur'),
	 (19,'Belitung'),
	 (19,'Bangka Barat'),
	 (19,'Bangka'),
	 (19,'Pangkal Pinang'),
	 (36,'Serang, Kab.'),
	 (36,'Cilegon'),
	 (36,'Lebak'),
	 (36,'Pandeglang');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (36,'Serang, Kota'),
	 (36,'Tangerang, Kab.'),
	 (36,'Tangerang Selatan'),
	 (36,'Tangerang, Kota'),
	 (17,'Kepahiang'),
	 (17,'Lebong'),
	 (17,'Rejang Lebong'),
	 (17,'Kaur'),
	 (17,'Seluma'),
	 (17,'Muko Muko');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (17,'Bengkulu Utara'),
	 (17,'Bengkulu Selatan'),
	 (17,'Bengkulu Tengah'),
	 (17,'Bengkulu'),
	 (34,'Gunung Kidul'),
	 (34,'Bantul'),
	 (34,'Kulon Progo'),
	 (34,'Sleman'),
	 (34,'Yogyakarta'),
	 (31,'Kepulauan Seribu');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (31,'Jakarta Utara'),
	 (31,'Jakarta Timur'),
	 (31,'Jakarta Selatan'),
	 (31,'Jakarta Barat'),
	 (31,'Jakarta Pusat'),
	 (75,'Bone Bolango'),
	 (75,'Gorontalo Utara'),
	 (75,'Pohuwato'),
	 (75,'Gorontalo, Kab.'),
	 (75,'Boalemo');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (75,'Gorontalo, Kota'),
	 (15,'Tebo'),
	 (15,'Sarolangun'),
	 (15,'Merangin'),
	 (15,'Bungo'),
	 (15,'Kerinci'),
	 (15,'Sungaipenuh'),
	 (15,'Tanjung Jabung Timur'),
	 (15,'Batang Hari'),
	 (15,'Tanjung Jabung Barat');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (15,'Muaro Jambi'),
	 (15,'Jambi'),
	 (32,'Tasikmalaya, Kab.'),
	 (32,'Tasikmalaya, Kota'),
	 (32,'Pangandaran'),
	 (32,'Ciamis'),
	 (32,'Banjar'),
	 (32,'Cirebon, Kab.'),
	 (32,'Kuningan'),
	 (32,'Majalengka');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (32,'Sumedang'),
	 (32,'Indramayu'),
	 (32,'Cirebon, Kota'),
	 (32,'Garut'),
	 (32,'Sukabumi, Kab.'),
	 (32,'Cianjur'),
	 (32,'Sukabumi, Kota'),
	 (32,'Karawang'),
	 (32,'Subang'),
	 (32,'Purwakarta');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (32,'Bandung, Kab.'),
	 (32,'Bandung, Kota'),
	 (32,'Bandung Barat'),
	 (32,'Cimahi'),
	 (32,'Bekasi, Kab.'),
	 (32,'Bekasi, Kota'),
	 (32,'Bogor, Kab.'),
	 (32,'Depok'),
	 (32,'Bogor, Kota'),
	 (33,'Demak');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (33,'Jepara'),
	 (33,'Kudus'),
	 (33,'Rembang'),
	 (33,'Pati'),
	 (33,'Blora'),
	 (33,'Grobogan'),
	 (33,'Karanganyar'),
	 (33,'Wonogiri'),
	 (33,'Sukoharjo'),
	 (33,'Klaten');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (33,'Boyolali'),
	 (33,'Sragen'),
	 (33,'Surakarta (Solo)'),
	 (33,'Magelang, Kab.'),
	 (33,'Wonosobo'),
	 (33,'Temanggung'),
	 (33,'Magelang, Kota'),
	 (33,'Kebumen'),
	 (33,'Purworejo'),
	 (33,'Banjarnegara');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (33,'Purbalingga'),
	 (33,'Cilacap'),
	 (33,'Banyumas'),
	 (33,'Tegal, Kab.'),
	 (33,'Pemalang'),
	 (33,'Brebes'),
	 (33,'Tegal, Kota'),
	 (33,'Kendal'),
	 (33,'Batang'),
	 (33,'Pekalongan, Kab.');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (33,'Pekalongan, Kota'),
	 (33,'Semarang, Kab.'),
	 (33,'Semarang, Kota'),
	 (33,'Salatiga'),
	 (35,'Sumenep'),
	 (35,'Pamekasan'),
	 (35,'Sampang'),
	 (35,'Bangkalan'),
	 (35,'Banyuwangi'),
	 (35,'Situbondo');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (35,'Bondowoso'),
	 (35,'Jember'),
	 (35,'Lumajang'),
	 (35,'Probolinggo, Kab.'),
	 (35,'Probolinggo, Kota'),
	 (35,'Pasuruan, Kab.'),
	 (35,'Pasuruan, Kota'),
	 (35,'Trenggalek'),
	 (35,'Tulungagung'),
	 (35,'Blitar, Kab.');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (35,'Blitar, Kota'),
	 (35,'Malang, Kab.'),
	 (35,'Batu'),
	 (35,'Malang, Kota'),
	 (35,'Nganjuk'),
	 (35,'Kediri, Kab.'),
	 (35,'Kediri, Kota'),
	 (35,'Pacitan'),
	 (35,'Ponorogo'),
	 (35,'Magetan');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (35,'Ngawi'),
	 (35,'Madiun, Kab.'),
	 (35,'Madiun, Kota'),
	 (35,'Tuban'),
	 (35,'Lamongan'),
	 (35,'Bojonegoro'),
	 (35,'Jombang'),
	 (35,'Mojokerto, Kab.'),
	 (35,'Mojokerto, Kota'),
	 (35,'Sidoarjo');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (35,'Gresik'),
	 (35,'Surabaya'),
	 (61,'Melawi'),
	 (61,'Sekadau'),
	 (61,'Sambas'),
	 (61,'Landak'),
	 (61,'Bengkayang'),
	 (61,'Singkawang'),
	 (61,'Mempawah'),
	 (61,'Ketapang');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (61,'Kayong Utara'),
	 (61,'Kapuas Hulu'),
	 (61,'Sintang'),
	 (61,'Sanggau'),
	 (61,'Kubu Raya'),
	 (61,'Pontianak, Kota'),
	 (63,'Tanah Bumbu'),
	 (63,'Kotabaru'),
	 (63,'Tabalong'),
	 (63,'Balangan');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (63,'Hulu Sungai Utara'),
	 (63,'Hulu Sungai Tengah'),
	 (63,'Hulu Sungai Selatan'),
	 (63,'Banjar'),
	 (63,'Tapin'),
	 (63,'Tanah Laut'),
	 (63,'Banjarbaru'),
	 (63,'Barito Kuala'),
	 (63,'Banjarmasin'),
	 (62,'Pulang Pisau');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (62,'Lamandau'),
	 (62,'Kapuas'),
	 (62,'Gunung Mas'),
	 (62,'Katingan'),
	 (62,'Kotawaringin Timur'),
	 (62,'Seruyan'),
	 (62,'Kotawaringin Barat'),
	 (62,'Sukamara'),
	 (62,'Murung Raya'),
	 (62,'Barito Utara');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (62,'Barito Selatan'),
	 (62,'Barito Timur'),
	 (62,'Palangka Raya'),
	 (64,'Berau'),
	 (64,'Samarinda'),
	 (64,'Penajam Paser Utara'),
	 (64,'Paser'),
	 (64,'Balikpapan'),
	 (64,'Kutai Kartanegara'),
	 (64,'Mahakam Ulu');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (64,'Kutai Barat'),
	 (64,'Kutai Timur'),
	 (64,'Bontang'),
	 (65,'Malinau'),
	 (65,'Nunukan'),
	 (65,'Tana Tidung'),
	 (65,'Bulungan (Bulongan)'),
	 (65,'Tarakan'),
	 (21,'Lingga'),
	 (21,'Kepulauan Anambas');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (21,'Natuna'),
	 (21,'Karimun'),
	 (21,'Batam'),
	 (21,'Bintan'),
	 (21,'Tanjung Pinang'),
	 (18,'Tanggamus'),
	 (18,'Pringsewu'),
	 (18,'Lampung Selatan'),
	 (18,'Lampung Tengah'),
	 (18,'Pesawaran');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (18,'Bandar Lampung'),
	 (18,'Lampung Barat'),
	 (18,'Pesisir Barat'),
	 (18,'Way Kanan'),
	 (18,'Mesuji'),
	 (18,'Tulang Bawang Barat'),
	 (18,'Tulang Bawang'),
	 (18,'Lampung Utara'),
	 (18,'Lampung Timur'),
	 (18,'Metro');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (82,'Halmahera Timur'),
	 (82,'Halmahera Tengah'),
	 (82,'Tidore Kepulauan'),
	 (82,'Kepulauan Sula'),
	 (82,'Pulau Taliabu'),
	 (82,'Halmahera Selatan'),
	 (82,'Pulau Morotai'),
	 (82,'Halmahera Utara'),
	 (82,'Halmahera Barat'),
	 (82,'Ternate');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (81,'Kepulauan Aru'),
	 (81,'Maluku Tenggara'),
	 (81,'Tual'),
	 (81,'Maluku Barat Daya'),
	 (81,'Seram Bagian Timur'),
	 (81,'Maluku Tengah'),
	 (81,'Buru'),
	 (81,'Buru Selatan'),
	 (81,'Seram Bagian Barat'),
	 (81,'Maluku Tenggara Barat');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (81,'Ambon'),
	 (11,'Aceh Singkil'),
	 (11,'Subulussalam'),
	 (11,'Aceh Tenggara'),
	 (11,'Gayo Lues'),
	 (11,'Bener Meriah'),
	 (11,'Aceh Tengah'),
	 (11,'Aceh Tamiang'),
	 (11,'Aceh Timur'),
	 (11,'Langsa');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (11,'Aceh Utara'),
	 (11,'Lhokseumawe'),
	 (11,'Bireuen'),
	 (11,'Pidie Jaya'),
	 (11,'Pidie'),
	 (11,'Aceh Besar'),
	 (11,'Simeulue'),
	 (11,'Aceh Selatan'),
	 (11,'Aceh Barat Daya'),
	 (11,'Aceh Barat');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (11,'Nagan Raya'),
	 (11,'Aceh Jaya'),
	 (11,'Sabang'),
	 (11,'Banda Aceh'),
	 (52,'Sumbawa Barat'),
	 (52,'Sumbawa'),
	 (52,'Dompu'),
	 (52,'Bima, Kab.'),
	 (52,'Bima, Kota'),
	 (52,'Lombok Timur');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (52,'Lombok Tengah'),
	 (52,'Mataram'),
	 (52,'Lombok Barat'),
	 (52,'Lombok Utara'),
	 (53,'Sumba Barat'),
	 (53,'Sumba Tengah'),
	 (53,'Sumba Barat Daya'),
	 (53,'Sumba Timur'),
	 (53,'Manggarai Barat'),
	 (53,'Lembata');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (53,'Manggarai'),
	 (53,'Manggarai Timur'),
	 (53,'Nagekeo'),
	 (53,'Ngada'),
	 (53,'Ende'),
	 (53,'Flores Timur'),
	 (53,'Sikka'),
	 (53,'Rote Ndao'),
	 (53,'Alor'),
	 (53,'Belu');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (53,'Malaka'),
	 (53,'Timor Tengah Utara'),
	 (53,'Timor Tengah Selatan'),
	 (53,'Sabu Raijua'),
	 (53,'Kupang, Kab.'),
	 (53,'Kupang, Kota'),
	 (91,'Fakfak'),
	 (91,'Kaimana'),
	 (91,'Maybrat'),
	 (91,'Raja Ampat');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (91,'Tambrauw'),
	 (91,'Sorong, Kab.'),
	 (91,'Sorong Selatan'),
	 (91,'Sorong, Kota'),
	 (91,'Teluk Bintuni'),
	 (91,'Teluk Wondama'),
	 (91,'Manokwari Selatan'),
	 (91,'Pegunungan Arfak'),
	 (91,'Manokwari'),
	 (94,'Mimika');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (94,'Mappi'),
	 (94,'Asmat'),
	 (94,'Boven Digoel'),
	 (94,'Merauke'),
	 (94,'Yalimo'),
	 (94,'Yahukimo'),
	 (94,'Pegunungan Bintang'),
	 (94,'Nduga'),
	 (94,'Tolikara'),
	 (94,'Lanny Jaya');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (94,'Jayawijaya'),
	 (94,'Mamberamo Tengah'),
	 (94,'Keerom'),
	 (94,'Mamberamo Raya'),
	 (94,'Sarmi'),
	 (94,'Jayapura, Kab.'),
	 (94,'Jayapura, Kota'),
	 (94,'Puncak'),
	 (94,'Puncak Jaya'),
	 (94,'Dogiyai');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (94,'Nabire'),
	 (94,'Intan Jaya'),
	 (94,'Paniai'),
	 (94,'Deiyai (Deliyai)'),
	 (94,'Waropen'),
	 (94,'Kepulauan Yapen (Yapen Waropen)'),
	 (94,'Biak Numfor'),
	 (94,'Supiori'),
	 (14,'Kuantan Singingi'),
	 (14,'Indragiri Hulu');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (14,'Indragiri Hilir'),
	 (14,'Rokan Hilir'),
	 (14,'Dumai'),
	 (14,'Bengkalis'),
	 (14,'Siak'),
	 (14,'Kepulauan Meranti'),
	 (14,'Rokan Hulu'),
	 (14,'Kampar'),
	 (14,'Pelalawan'),
	 (14,'Pekanbaru');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (76,'Polewali Mandar'),
	 (76,'Mamuju Utara'),
	 (76,'Mamuju'),
	 (76,'Majene'),
	 (76,'Mamasa'),
	 (73,'Luwu Timur'),
	 (73,'Luwu Utara'),
	 (73,'Selayar (Kepulauan Selayar)'),
	 (73,'Bone'),
	 (73,'Maros');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (73,'Sinjai'),
	 (73,'Bulukumba'),
	 (73,'Jeneponto'),
	 (73,'Bantaeng'),
	 (73,'Takalar'),
	 (73,'Gowa'),
	 (73,'Toraja Utara'),
	 (73,'Luwu'),
	 (73,'Palopo'),
	 (73,'Tana Toraja');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (73,'Enrekang'),
	 (73,'Sidenreng Rappang/Rapang'),
	 (73,'Pinrang'),
	 (73,'Parepare'),
	 (73,'Wajo'),
	 (73,'Soppeng'),
	 (73,'Barru'),
	 (73,'Pangkajene Kepulauan'),
	 (73,'Makassar'),
	 (72,'Morowali');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (72,'Banggai Kepulauan'),
	 (72,'Banggai'),
	 (72,'Tojo Una-Una'),
	 (72,'Poso'),
	 (72,'Buol'),
	 (72,'Toli-Toli'),
	 (72,'Parigi Moutong'),
	 (72,'Sigi'),
	 (72,'Donggala'),
	 (72,'Palu');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (74,'Kolaka Utara'),
	 (74,'Kolaka'),
	 (74,'Konawe Selatan'),
	 (74,'Wakatobi'),
	 (74,'Bombana'),
	 (74,'Buton Tengah'),
	 (74,'Konawe'),
	 (74,'Bau-Bau'),
	 (74,'Buton'),
	 (74,'Buton Selatan');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (74,'Muna'),
	 (74,'Buton Utara'),
	 (74,'Konawe Utara'),
	 (74,'Kendari'),
	 (71,'Minahasa Selatan'),
	 (71,'Minahasa Tenggara'),
	 (71,'Kepulauan Talaud'),
	 (71,'Kepulauan Siau Tagulandang Biaro (Sitaro)'),
	 (71,'Kepulauan Sangihe'),
	 (71,'Bolaang Mongondow Timur');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (71,'Bolaang Mongondow Selatan'),
	 (71,'Bolaang Mongondow (Bolmong)'),
	 (71,'Bolaang Mongondow Utara'),
	 (71,'Kotamobagu'),
	 (71,'Minahasa'),
	 (71,'Bitung'),
	 (71,'Tomohon'),
	 (71,'Minahasa Utara'),
	 (71,'Manado'),
	 (13,'Solok Selatan');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (13,'Dharmasraya'),
	 (13,'Sijunjung (Sawah Lunto Sijunjung)'),
	 (13,'Sawah Lunto'),
	 (13,'Solok, Kab.'),
	 (13,'Solok, Kota'),
	 (13,'Tanah Datar'),
	 (13,'Padang Panjang'),
	 (13,'Pasaman Barat'),
	 (13,'Agam'),
	 (13,'Pasaman');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (13,'Lima Puluh Koto/Kota'),
	 (13,'Payakumbuh'),
	 (13,'Bukittinggi'),
	 (13,'Pesisir Selatan'),
	 (13,'Padang Pariaman'),
	 (13,'Pariaman'),
	 (13,'Kepulauan Mentawai'),
	 (13,'Padang'),
	 (16,'Ogan Komering Ulu Timur'),
	 (16,'Ogan Komering Ulu Selatan');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (16,'Ogan Komering Ulu'),
	 (16,'Muara Enim'),
	 (16,'Musi Rawas Utara'),
	 (16,'Musi Rawas'),
	 (16,'Lubuk Linggau'),
	 (16,'Empat Lawang'),
	 (16,'Lahat'),
	 (16,'Pagar Alam'),
	 (16,'Penukal Abab Lematang Ilir'),
	 (16,'Prabumulih');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (16,'Banyuasin'),
	 (16,'Ogan Ilir'),
	 (16,'Musi Banyuasin'),
	 (16,'Ogan Komering Ilir'),
	 (16,'Palembang'),
	 (12,'Mandailing Natal'),
	 (12,'Nias Selatan'),
	 (12,'Nias'),
	 (12,'Nias Barat'),
	 (12,'Gunungsitoli');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (12,'Nias Utara'),
	 (12,'Padang Lawas'),
	 (12,'Tapanuli Selatan'),
	 (12,'Padang Lawas Utara'),
	 (12,'Padang Sidempuan'),
	 (12,'Tapanuli Tengah'),
	 (12,'Sibolga'),
	 (12,'Tapanuli Utara'),
	 (12,'Humbang Hasundutan'),
	 (12,'Samosir');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (12,'Toba Samosir'),
	 (12,'Dairi'),
	 (12,'Pakpak Bharat'),
	 (12,'Karo'),
	 (12,'Labuhan Batu Utara'),
	 (12,'Labuhan Batu'),
	 (12,'Labuhan Batu Selatan'),
	 (12,'Asahan'),
	 (12,'Tanjung Balai'),
	 (12,'Batu Bara');
INSERT INTO lk_city (provinceID,cityName) VALUES
	 (12,'Simalungun'),
	 (12,'Pematang Siantar'),
	 (12,'Serdang Bedagai'),
	 (12,'Langkat'),
	 (12,'Binjai'),
	 (12,'Tebing Tinggi'),
	 (12,'Deli Serdang'),
	 (12,'Medan');
