INSERT INTO lk_province (provinceName,countryID) VALUES
	 ('ACEH',1),
	 ('SUMATERA UTARA',1),
	 ('SUMATERA BARAT',1),
	 ('RIAU',1),
	 ('JAMBI',1),
	 ('SUMATERA SELATAN',1),
	 ('BENGKULU',1),
	 ('LAMPUNG',1),
	 ('BANGKA BELITUNG',1),
	 ('KEPULAUAN RIAU',1);
INSERT INTO lk_province (provinceName,countryID) VALUES
	 ('DKI JAKARTA',1),
	 ('JAWA BARAT',1),
	 ('JAWA TENGAH',1),
	 ('DI YOGYAKARTA',1),
	 ('JAWA TIMUR',1),
	 ('BANTEN',1),
	 ('BALI',1),
	 ('NUSA TENGGARA BARAT',1),
	 ('NUSA TENGGARA TIMUR',1),
	 ('KALIMANTAN BARAT',1);
INSERT INTO lk_province (provinceName,countryID) VALUES
	 ('KALIMANTAN TENGAH',1),
	 ('KALIMANTAN SELATAN',1),
	 ('KALIMANTAN TIMUR',1),
	 ('KALIMANTAN UTARA',1),
	 ('SULAWESI UTARA',1),
	 ('SULAWESI TENGAH',1),
	 ('SULAWESI SELATAN',1),
	 ('SULAWESI TENGGARA',1),
	 ('GORONTALO',1),
	 ('SULAWESI BARAT',1);
INSERT INTO lk_province (provinceName,countryID) VALUES
	 ('MALUKU',1),
	 ('MALUKU UTARA',1),
	 ('PAPUA BARAT',1),
	 ('PAPUA',1);
